name: animated_scrollable
description: Um scaffold com header animado para Flutter. Crie cabeÃ§alhos que encolhem e reagem ao scroll de forma simples, com controle de porcentagem e rodapÃ© fixo
version: 1.0.2
homepage: https://github.com/viniciussoaresm/animated_scrollable_lib

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - ui
  - animacao
  - scroll
  - header
  - interface